### ISSUE TITLE
I am the bone of my sword.

### ISSUE THREAD

**Issue by operando** [operando/DroidKaigi#13]

**Comment by konifar** [comment]
半端なく終わる気がしないですが、続々と登壇者の資料が上がってきているようでめちゃくちゃ焦っています

**Comment by operando** [comment]
慌てるな！
終わったとみせかけて他の登壇者を焦らせる高度な心理戦かもしれない。(んなアホな

**Comment by operando** [comment]
まあ俺が終わってないことで他の登壇者を安心させる作戦だからね！(うるせぇ...

**Comment by konifar** [comment]
「ーー人は時に 、健気に生きているだけで、誰かを救っていることがある」 容疑者Xの献身 東野圭吾

**Comment by operando** [comment]
深い！！
