### ISSUE TITLE
ねぇ、秒速5センチなんだって。

### ISSUE THREAD

**Issue by operando** [operando/DroidKaigi#21]
明里 < ねぇ、秒速5センチなんだって。
隆貴 < えっ、なに？
明里 < 一枚のスライドができるスピード。秒速5センチメートル。

**Comment by konifar** [comment]
僕たちの前にはいまだ巨大すぎるIssueが、茫漠とした時間が、どうしようもなく横たわっていた。

**Comment by operando** [comment]
2017もいきたい、いきたい！！
