### ISSUE TITLE
ゆっくり話す

### ISSUE THREAD

**Issue by operando** [operando/DroidKaigi#6]
去年早く話しすぎて時間余った。
25分 / 160枚のスライドで時間余らせるとかアホすぎる。
学習しろ、おれ。

**Comment by konifar** [comment]
半端ないwww

**Comment by operando** [comment]
どうやってもスライドの枚数は増えていく....

**Comment by operando** [comment]
逆にゆっくり過ぎた。というかDemoに手こずりすぎたか。
明日は普通 + DemoはGif or 動画でいく。

**Comment by operando** [comment]
一日目のセッションは最初ゆっくりすぎて間に合わなくて、二日目は飛ばしすぎて時間余った。
なんだこれ。時間配分難しい。
